   <section id="index-container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2" id="index-wrapper">
                <div class="panel panel-primary animated flipInY">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center">     
                            SEJA BEM VINDO
                        </h3>      
                    </div>
                    <div class="panel-body">
                        <h4>
                            Uhull! Você instalou e configurou o HXPHP Framework com sucesso!
                        </h4>
                        <p>
                            Agora acesse a <a class="btn btn-success btn-xs" href="http://www.hxtutors.com.br/curso/dominando-o-hxphp-framework/" title="Acesse o curso completo sobre HXPHP" target="_blank">área de membros</a> e assista ao nosso curso oficial para dominar completamente esta poderosa ferramenta.
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </section>
