-- MySQL Script generated by MySQL Workbench
-- 01/08/15 16:50:49
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hxphp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hxphp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hxphp` ;

-- -----------------------------------------------------
-- Table `hxphp`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hxphp`.`states` (
  `id` INT(2) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(20) CHARACTER SET 'latin1' COLLATE 'latin1_general_cs' NOT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hxphp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hxphp`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `state_id` INT NOT NULL,
  `password` CHAR(128) NOT NULL,
  `salt` CHAR(128) NOT NULL,
  `obs` MEDIUMTEXT NULL,
  `role` VARCHAR(45) NOT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_state_id_idx` (`state_id` ASC),
  CONSTRAINT `users_state_id`
    FOREIGN KEY (`state_id`)
    REFERENCES `hxphp`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hxphp`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hxphp`.`login_attempts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `IP` VARCHAR(20) NOT NULL,
  `time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `login_attempts_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `hxphp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hxphp`.`lost_passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hxphp`.`lost_passwords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `IP` VARCHAR(20) NOT NULL,
  `token` CHAR(128) NOT NULL,
  `data` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `lost_password_user_id_idx` (`user_id` ASC),
  CONSTRAINT `lost_password_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `hxphp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hxphp`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hxphp`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `observacoes` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `projects_user_id_idx` (`user_id` ASC),
  CONSTRAINT `projects_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `hxphp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hxphp`.`states`
-- -----------------------------------------------------
START TRANSACTION;
USE `hxphp`;
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (1, 'Acre', 'AC');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (2, 'Alagoas', 'AL');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (3, 'Amazonas', 'AM');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (4, 'Amapá', 'AP');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (5, 'Bahia', 'BA');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (6, 'Ceará', 'CE');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (7, 'Distrito Federal', 'DF');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (8, 'Espírito Santo', 'ES');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (9, 'Goiás', 'GO');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (10, 'Maranhão', 'MA');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (11, 'Minas Gerais', 'MG');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (12, 'Mato Grosso do Sul', 'MS');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (13, 'Mato Grosso', 'MT');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (14, 'Pará', 'PA');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (15, 'Paraíba', 'PB');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (16, 'Pernambuco', 'PE');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (17, 'Piauí', 'PI');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (18, 'Paraná', 'PR');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (19, 'Rio de Janeiro', 'RJ');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (20, 'Rio Grande do Norte', 'RN');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (21, 'Rondônia', 'RO');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (22, 'Roraima', 'RR');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (23, 'Rio Grande do Sul', 'RS');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (24, 'Santa Catarina', 'SC');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (25, 'Sergipe', 'SE');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (26, 'São Paulo', 'SP');
INSERT INTO `hxphp`.`states` (`id`, `estado`, `sigla`) VALUES (27, 'Tocantis', 'TO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `hxphp`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `hxphp`;
INSERT INTO `hxphp`.`users` (`id`, `full_name`, `username`, `email`, `state_id`, `password`, `salt`, `obs`, `role`, `status`) VALUES (1, 'Bruno C. Santos', 'administrador', 'contato@hxphp.com.br', 25, '1fd149d21dd5e8072d12b5d6b4eb316e66e94409ddb4858ee7ed019ff2756e91ee2c5b0d9a4bb641f27f61238b1181a7bac43210c8a26dc66ac6538c00d06c45', 'bac4e9c259ac3acee88a679899062cd85e32493ff3d1109720ea459a62f5ef3166427612a167f29ab3e1e8d8f46c6b5409f1304be97cbf4b4fd5f5d55bdf55f9', NULL, 'administrator', 0);

COMMIT;

