<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Bruno C. Santos">
	<meta name="generator" content="HXPHP Framework">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $view_title; ?></title>
	<link rel="shortcut icon" href="<?php echo IMG; ?>favicon.ico" type="image/x-icon">
	<?php echo $add_css; ?>
	<link rel="stylesheet" href="<?php echo CSS; ?>bootstrap.min.css" type="text/css">
	<?php echo $add_js; ?>
</head>
<body>
	<div class="full bg" id="header">
		<div class="container">
			<div class="col-md-12">
				<a href="<?php echo SITE; ?>" class="logo col-md-offset-4 col-md-4">
					<div class="col-md-10 col-md-offset-1">
						<img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
					</div>
				</a>
			</div>
		</div>
	</div>
	<br>
	<br>

	<div class="container">
			<div class="col-md-12">